let map,shelters=[],currentLat,currentLng,currentMarker,nearestMarker,routeLine,allMarkers=[];
const nearestInfo=document.getElementById("nearestInfo"),top5=document.getElementById("top5");
function distance(lat1,lng1,lat2,lng2){const R=6371,dLat=(lat2-lat1)*Math.PI/180,dLng=(lng2-lng1)*Math.PI/180,a=Math.sin(dLat/2)**2+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
fetch("data.json").then(res=>{if(!res.ok)throw new Error("data.jsonが見つかりません");return res.json();}).then(data=>{shelters=data.shelters||[];if(shelters.length===0)throw new Error("避難所データがありません");getLocation();}).catch(err=>{nearestInfo.innerHTML=`<p class="error">${err.message}</p>`;});
function getLocation(){if(!navigator.geolocation){nearestInfo.innerHTML='<p class="error">このブラウザは位置情報に対応していません。</p>';return;}navigator.geolocation.getCurrentPosition(pos=>{currentLat=pos.coords.latitude;currentLng=pos.coords.longitude;findNearest();},()=>{nearestInfo.innerHTML='<p class="error">位置情報が取得できません。ブラウザの位置情報を許可してください。</p>';},{enableHighAccuracy:true,maximumAge:0,timeout:10000});}
function findNearest(){shelters.forEach(s=>{s.distance=distance(currentLat,currentLng,Number(s.lat),Number(s.lng));});shelters.sort((a,b)=>a.distance-b.distance);const nearest=shelters[0];showNearest(nearest);showTop5();drawMap(nearest);}
function showNearest(s){nearestInfo.innerHTML=`<h3>${s.name}</h3><p><b>住所</b><br>${s.address||"住所不明"}</p><p><b>収容人数</b><br>${s.capacity??"不明"} 人</p><p><b>現在地からの距離</b><br>${s.distance.toFixed(2)} km</p><button onclick="window.open('https://www.google.com/maps?q=${s.lat},${s.lng}','_blank')">Googleマップで開く</button>`;}
function showTop5(){top5.innerHTML=shelters.slice(0,5).map((s,i)=>`<li><b>${i+1}位：${s.name}</b><br>${s.address||""}<br>${s.distance.toFixed(2)} km</li>`).join("");}
function drawMap(nearest){if(!map){map=L.map("map");L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"OpenStreetMap"}).addTo(map);}allMarkers.forEach(m=>map.removeLayer(m));allMarkers=[];if(currentMarker)map.removeLayer(currentMarker);if(nearestMarker)map.removeLayer(nearestMarker);if(routeLine)map.removeLayer(routeLine);shelters.forEach(s=>{const marker=L.marker([s.lat,s.lng]).addTo(map).bindPopup(`<b>${s.name}</b><br>${s.address||""}<br>${s.distance.toFixed(2)} km`);allMarkers.push(marker);});currentMarker=L.circleMarker([currentLat,currentLng],{radius:8,color:"blue",fillColor:"blue",fillOpacity:1}).addTo(map).bindPopup("現在地");nearestMarker=L.circleMarker([nearest.lat,nearest.lng],{radius:10,color:"red",fillColor:"red",fillOpacity:1}).addTo(map).bindPopup(`最寄り避難所<br>${nearest.name}`);routeLine=L.polyline([[currentLat,currentLng],[nearest.lat,nearest.lng]],{color:"red",weight:4}).addTo(map);map.fitBounds(routeLine.getBounds(),{padding:[50,50]});}
